name: "Build Docker Image"
on:
  repository_dispatch:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build_registry_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install vcstool
      - name: Checkout repos
        run: |
          vcs import --recursive . < butia_minimal.repos
      - name: Log into registry
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull pre-built image
        run: |
          ./pull.sh
      - name: Build images
        run: |
          ./build.sh
      - name: Push images
        run: |
          ./push.sh   